### ISSUE TITLE
parallel retrieve switch mac table.

### ISSUE THREAD

**Issue by doublechiang** [doublechiang/repair_stas#5]
currently we query the switch sequentially to get the mac table. Use multiple thread to query the switch in parallel.

**Comment by doublechiang** [comment]
LD, currently they are running under my folder. Would you like to move somewhere else for easy to update? Also currently I am running git pull to update, do you prefer another approach to deploy the running version?

**Comment by LDQMF** [comment]
Yeah, I'll move the repair folder to a more accessible location later today probably during the TE team's lunch to avoid downtime. As for deployment, git pull should be fine to continue using in this environment.

**Comment by LDQMF** [comment]
- Moved the folder to a more accessible location by symlink in /repair/.
- Deployed latest version.
